-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.3.144
-- Module  Version: 7.5
-- Tue May 07 20:00:32 2019

-- parameterized module component declaration
component ramdq
    port (Clock: in  std_logic; ClockEn: in  std_logic; 
        Reset: in  std_logic; WE: in  std_logic; 
        Address: in  std_logic_vector(7 downto 0); 
        Data: in  std_logic_vector(7 downto 0); 
        Q: out  std_logic_vector(7 downto 0));
end component;

-- parameterized module component instance
__ : ramdq
    port map (Clock=>__, ClockEn=>__, Reset=>__, WE=>__, Address(7 downto 0)=>__, 
        Data(7 downto 0)=>__, Q(7 downto 0)=>__);
